// Synergy Page Translations
window.synergyTranslations = {
    en: {
        '홈': 'Home',
        '협력자': 'Synergy',
        '전체': 'All',
        '방과 후': 'After School',
        '저녁': 'Evening',
        '밤': 'Night',
        '오후': 'Afternoon',
        '캐릭터 검색...': 'Search character...',
        'Show Spoiler': 'Show Spoiler',
        '로딩 중...': 'Loading...',
        '데이터를 불러올 수 없습니다': 'Failed to load data',
        '왼쪽에서 캐릭터를 선택하세요': 'Select a character from the left',
        '검색 결과가 없습니다': 'No search results',
        '협력 보상': 'Synergy Rewards',
        '협력 이벤트': 'Synergy Events',
        '도시 이벤트': 'City Events',
        '기타 이벤트': 'Other Events',
        '기타 이벤트 (15랭크 이후)': 'Other Events (Rank 15+)',
        '선호 선물': 'Preferred Gifts',
        '선택': 'Choice',
        '랭크': 'Rank',
        '보상': 'Reward',
        '이름': 'Name',
        '호감도': 'Affection',
        '가격': 'Price',
        '효율': 'Efficiency',
        '할인가': 'DC Price',
        '할인 조건': 'DC Condition',
        '획득처': 'Source',
        '최대': 'Max',
        '갱신': 'Reset',
        'UNLOCK :': 'UNLOCK :',
        '이름/보상': 'Name/Reward',
        '이름/가격/획득처': 'Name/Price/Source',
        '(패치 예정)': '(Patch Pending)',
        // 캐릭터 이름 번역 (characters.js에 없는 경우)
        characters: {
            // 여기에 characters.js에 없는 캐릭터 이름 번역 추가
        }
    },
    jp: {
        '홈': 'ホーム',
        '협력자': 'シナジー',
        '전체': '全て',
        '방과 후': '放課後',
        '저녁': '夕方',
        '밤': '夜',
        '오후': '午後',
        '캐릭터 검색...': 'キャラクター検索...',
        'Show Spoiler': 'ネタバレ表示',
        '로딩 중...': '読み込み中...',
        '데이터를 불러올 수 없습니다': 'データの読み込みに失敗しました',
        '왼쪽에서 캐릭터를 선택하세요': '左からキャラクターを選択してください',
        '검색 결과가 없습니다': '検索結果がありません',
        '협력 보상': 'シナジーランクアップ報酬',
        '협력 이벤트': 'シナジーの選択肢',
        '도시 이벤트': '都市イベント',
        '기타 이벤트': 'その他イベント',
        '기타 이벤트 (15랭크 이후)': 'その他イベント (ランク15以降)',
        '선호 선물': '好みの贈り物',
        '선택': '選択',
        '랭크': 'ランク',
        '보상': '報酬',
        '이름': '名前',
        '호감도': '好感度',
        '가격': '価格',
        '효율': '効率',
        '할인가': '割引価格',
        '할인 조건': '割引条件',
        '획득처': '入手先',
        '최대': '最大',
        '갱신': 'リセット',
        'UNLOCK :': 'アンロック :',
        '이름/보상': '名前/報酬',
        '이름/가격/획득처': '名前/価格/入手先',
        '(패치 예정)': '(パッチ予定)',
        // 캐릭터 이름 번역 (characters.js에 없는 경우)
        characters: {
            // 여기에 characters.js에 없는 캐릭터 이름 번역 추가
        }
    }
};

