name = "lufelnet-tactic-cache"
main = "worker.mjs"
compatibility_date = "2026-10-01"
workers_dev = false

[[routes]]
pattern = "api.lufel.net"
custom_domain = true

[[d1_databases]]
binding = "CACHE_STATE"
database_name = "lufelnet-tactic-cache"
database_id = "fc859bab-0859-4ac7-bb63-f9449b27066d"

[vars]
ALLOWED_ORIGIN = "https://lufel.net"
SUPABASE_URL = "https://ipdkvuybgxczqwwmrqsw.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Hk_7I7kkgaAKrPLQz_sdUA_XvrKoJbI"
